import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'
import localFont from 'next/font/local'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const myFont = localFont({
  src: '../../fonts/helvetica-neue/HelveticaNeue-Medium.otf',
  display: 'swap',
})


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={myFont.className}>
      <body>{children}</body>
    </html>
  )
}
